feat: add OIDC configuration and general improvements
camptocamp/devops-stack-module-minio pull request #23
Opened 2023-05-12 08:34 UTC by lentidas

## Description of the changes

This PR adds the necessary configuration to make MinIO work with OIDC for accessing the web interface.
I also added the flag necessary to activate the ServiceMonitor after the first deployment.
Besides, I took the opportunity to do a patch upgrade of the Helm chart.

## Breaking change

- [x] No - Because the OIDC configuration **won't be required** although it is preferred and because the chart upgrade is **only a patch upgrade** (5.0.7 -> 5.0.9).

## Tests executed on which distribution(s)

- [x] KinD

2023-05-12 14:11 UTC, lentidas commented on locals.tf
> +      }, var.oidc.issuer_url != "" && var.oidc.client_id != "" && var.oidc.client_secret != "" ? merge({
I'm happy to receive alternatives on this line if you think there is a better/cleaner way.

2023-05-15 07:26 UTC, ckaenzig commented on locals.tf
> +      }, var.oidc.issuer_url != "" && var.oidc.client_id != "" && var.oidc.client_secret != "" ? merge({
I don't have a better solution for this condition, except maybe putting this in a validation function for the `oidc` module variable, and checking only one of the values here.

Other than that, this locals.tf file is quite hard to read because of the multiple conditions and `merge()` functions in a single huge 75 lines expression, and has some indentation issues which don't help. I think you should consider defining the various parts in separate locals and assembing them at the end using merges, something like that.

2023-05-15 07:31 UTC, ckaenzig commented
A general comment about devops stack PRs: since we're using "squash & merge"  when merging PRs, please create separate PRs for differents things (otherwise we end up with single commits that change many unrelated things which is not good practice) :
- adding a `enable_service_monitor` variable
- upgrading the minio chart
- adding the OIDC configuration
- general improvements / cleanup (this one could maybe be done within one of the other PRs)

2023-05-15 07:39 UTC, lentidas commented
> A general comment about devops stack PRs: since we're using "squash & merge" when merging PRs, please create separate PRs for differents things (otherwise we end up with single commits that change many unrelated things which is not good practice) :
> 
>     * adding a `enable_service_monitor` variable
> 
>     * upgrading the minio chart
> 
>     * adding the OIDC configuration
> 
>     * general improvements / cleanup (this one could maybe be done within one of the other PRs)

I was actually thinking of doing a _Rebase and Merge_ on this branch, that's why you see so many force pushes on the history of the PR, I was trying to keep the commit history clean in order to do a proper merge.

2023-05-15 13:10 UTC, ckaenzig requested changes

2023-05-15 13:10 UTC, ckaenzig commented on locals.tf
> +  }, local.self_signed_cert_enabled ? local.self_signed_cert : null)
I know I'm being picky, but a correct indentation in my mind would be:
```suggestion
    },
    local.self_signed_cert_enabled ? local.self_signed_cert : null
  )
```
Now if `terraform fmt` thinks otherwise, you should ignore my comment and leave it as it suggests.

2023-05-15 13:10 UTC, ckaenzig commented on locals.tf
> +    }, local.oidc_config.oidc.enabled ? local.oidc_config : null)
Same as above:
```suggestion
      },
      local.oidc_config.oidc.enabled ? local.oidc_config : null
    )
```

2023-05-15 13:14 UTC, ckaenzig approved these changes
Looks all good now :slightly_smiling_face: :+1:

2023-05-15 13:14 UTC, merged